site_name: Saps què és una trisquela?
site_url: https://mgfernan.com

nav:
  - Home: index.md
  - About me: about.md
  - Jocs de taula:
    - Cronocartes Història de Catalunya: jocs/cronocartes_catalunya.md

theme:
  name: material
  logo: assets/tryskele.png
  favicon: assets/favicon.ico

plugins:
  - social
  - blog:
      blog_dir: .

extra:
  analytics:
    provider: google
    property: G-J0Q5PFB35Q
  social:
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/cronocartes/
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/miquelgarciaf
    - icon: fontawesome/brands/mastodon
      link: https://mastodon.social/@mgfernan
    - icon: fontawesome/brands/github
      link: https://github.com/mgfernan/
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/miquelgarcia/

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - footnotes
