site_name: Saps què és una trisquela?

nav:
  - Home: index.md
  - About me: about.md

theme:
  name: material
  logo: assets/tryskele.png
favicon: favicon.ico

plugins:
  - blog:
      blog_dir: .

extra:
  analytics:
    provider: google
    property: G-802SVFWTGL

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
